"""
SQL comparison using sqlglot AST normalization + token similarity.

Responsibility: given two SQL strings (predicted vs gold), return two signals:
  - ast_match  (bool)  — structural equivalence after normalization
  - token_sim  (float) — Jaccard token overlap, a softer similarity score

These two signals serve different purposes in the eval pipeline:
  - ast_match  → pass/fail decision (did the model get it right?)
  - token_sim  → diagnostic metadata (how close was the wrong answer?)

Why two signals instead of one?
  ast_match is strict: "SELECT count(*) FROM customers" and
  "SELECT COUNT(*) FROM customers" are the same after normalization, but
  "SELECT COUNT(*) FROM orders" is not — even though it looks similar.
  token_sim captures that visual closeness (0.75) even when ast_match=False,
  which helps the critic and lesson generator understand the failure mode.

AST normalization via sqlglot:
  sqlglot.parse_one(sql).sql(dialect="duckdb") produces a canonical string:
    - uppercase keywords
    - normalized whitespace
    - consistent quoting
  Two structurally identical queries produce the same canonical string even if
  they were written with different casing, spacing, or alias names.

  Limitation: structurally different but semantically equivalent queries
  (e.g., different JOIN order, subquery vs CTE) will not match on ast_match.
  This is acceptable — the goal is correctness checking, not semantic equivalence.

Token similarity (Jaccard):
  tokens = lowercased whitespace-split words.
  Jaccard = |intersection| / |union|
  Range [0.0, 1.0]. Simple and fast. No external dependency.

  Known weakness: token order is ignored, so "SELECT a, b" and "SELECT b, a"
  score 1.0. Acceptable for our diagnostic use case — we only need a rough
  closeness score, not a precise edit distance.
"""

import sqlglot
from sqlglot.errors import ParseError


def compare(pred_sql: str, gold_sql: str) -> dict:
    """
    Compare a predicted SQL string against a gold SQL string.

    Args:
        pred_sql: SQL generated by the model.
        gold_sql: The correct gold SQL.

    Returns:
        A dict with two keys:
          {
            "ast_match": bool,   # True if structurally equivalent after normalization
            "token_sim": float,  # Jaccard token similarity in [0.0, 1.0]
          }

    Notes:
        - If either SQL fails to parse, ast_match=False and token_sim is still
          computed on the raw strings (useful signal even for malformed SQL).
        - Comparison is case-insensitive for token_sim.
    """
    return {
        "ast_match": _ast_match(pred_sql, gold_sql),
        "token_sim": _token_similarity(pred_sql, gold_sql),
    }


# ── AST match ─────────────────────────────────────────────────────────────────

def _normalize(sql: str) -> str | None:
    """
    Parse and re-serialize SQL using the DuckDB dialect.

    Returns the normalized SQL string, or None if parsing fails.
    Normalization: uppercase keywords, consistent spacing and quoting.
    """
    try:
        return sqlglot.parse_one(sql, dialect="duckdb").sql(dialect="duckdb")
    except (ParseError, Exception):
        return None


def _ast_match(pred_sql: str, gold_sql: str) -> bool:
    """
    Return True if both SQL strings normalize to the same canonical form.

    False if either fails to parse, or if the normalized strings differ.
    """
    pred_norm = _normalize(pred_sql)
    gold_norm = _normalize(gold_sql)

    if pred_norm is None or gold_norm is None:
        return False

    return pred_norm == gold_norm


# ── Token similarity ──────────────────────────────────────────────────────────

def _tokenize(sql: str) -> set[str]:
    """Split SQL into a set of lowercase tokens."""
    return set(sql.lower().split())


def _token_similarity(pred_sql: str, gold_sql: str) -> float:
    """
    Jaccard similarity between the token sets of two SQL strings.

    Jaccard = |intersection| / |union|

    Returns 0.0 if both strings are empty.
    Returns 1.0 if both token sets are identical.
    """
    pred_tokens = _tokenize(pred_sql)
    gold_tokens = _tokenize(gold_sql)

    union = pred_tokens | gold_tokens
    if not union:
        return 0.0

    intersection = pred_tokens & gold_tokens
    return len(intersection) / len(union)
