"""
SQL failure critic.

Responsibility: given a failed NLQ + pred_sql + gold_sql triplet, ask the LLM
to identify the specific errors. Returns a plain string — a numbered list of
concrete mistakes. This is the first step of the two-step critic → lesson pipeline.

Why a separate critic step instead of generating the lesson directly?
  Asking the LLM to produce a structured lesson in one shot causes it to fixate
  on the specific failure details rather than abstracting a generalizable pattern.
  The critic forces explicit error extraction first. The lesson generator then has
  labeled, concrete errors to abstract from — producing far better fix_rules.

Design decisions:
  - analyze() takes an LLMClient as argument (dependency injection), consistent
    with generator.py. No module-level client state.
  - Returns str (raw error text), not a parsed structure. The errors feed directly
    into build_lesson_gen_prompt() as a text block — parsing adds no value here.
  - Temperature = 0.0. Critic output must be precise and deterministic. We want
    the most accurate diagnosis, not creative variation.
  - LLMError propagates upward. The eval loop decides how to handle API failures.
"""

from app.llm.claude_client import LLMClient
from app.llm.prompts import build_critic_prompt


def analyze(client: LLMClient, nlq: str, pred_sql: str, gold_sql: str) -> str:
    """
    Identify the specific errors in a wrong SQL prediction.

    Calls the LLM critic prompt and returns the raw error list as a string.
    The output is a numbered list of concrete mistakes, e.g.:
        1. Used MONTH(order_date) which is not a valid DuckDB function
        2. Filter boundary should be start of last month, not current date

    Args:
        client:   Shared LLMClient instance.
        nlq:      The natural language question that was asked.
        pred_sql: The SQL generated by the model (wrong).
        gold_sql: The correct gold SQL.

    Returns:
        A plain string listing the errors. Non-empty if the LLM found mistakes.

    Raises:
        LLMError: if the Claude API call fails.
    """
    system, human = build_critic_prompt(nlq, pred_sql, gold_sql)
    return client.complete(system, human, temperature=0.0)
