"""
Lesson generator — produces a structured Lesson object from a SQL failure.

This is the second step of the two-step critic → lesson pipeline:
  1. critic.analyze()     → errors: str  (what went wrong, specifically)
  2. generate_lesson()    → Lesson        (generalizable rule for the future)

The LLM is asked to output a JSON object matching the Lesson schema. The response
is parsed, validated with Pydantic, and returned as a Lesson instance ready to be
stored in SQLite and indexed in FAISS Index 2.

Design decisions:
  - LessonGenerationError is raised on any failure: JSON parse error, missing
    field, wrong type, or empty response. The raw LLM output is attached so the
    eval loop can log it for debugging without losing context.
  - json.loads() + Lesson(**data) is the full validation chain. Pydantic catches
    missing required fields and type mismatches. No manual field checking needed.
  - _extract_json() uses regex to find the JSON object within the response. This
    handles cases where the LLM adds leading prose or a trailing sentence despite
    instructions. It does NOT handle nested JSON — the lesson schema is flat enough
    that a simple greedy {.*} match works.
  - Temperature = 0.0. Lesson generation must be deterministic and precise.
    Creative variation would produce inconsistent fix_rules across similar failures.
"""

import json
import re

from app.db.models import Lesson
from app.llm.claude_client import LLMClient
from app.llm.prompts import build_lesson_gen_prompt


class LessonGenerationError(Exception):
    """
    Raised when the LLM response cannot be parsed into a valid Lesson.

    Attributes:
        raw_output: The raw string returned by the LLM, for debugging.
    """

    def __init__(self, message: str, raw_output: str = "") -> None:
        super().__init__(message)
        self.raw_output = raw_output


def generate_lesson(
    client: LLMClient,
    nlq: str,
    pred_sql: str,
    gold_sql: str,
    errors: str,
) -> Lesson:
    """
    Generate a structured, reusable lesson from a SQL generation failure.

    Calls the LLM lesson gen prompt, parses the JSON response, and returns
    a validated Lesson Pydantic object ready for storage.

    Args:
        client:   Shared LLMClient instance.
        nlq:      The natural language question that was asked.
        pred_sql: The SQL generated by the model (wrong).
        gold_sql: The correct gold SQL.
        errors:   The critic's error list (output of critic.analyze()).

    Returns:
        A Lesson instance with all fields populated.

    Raises:
        LessonGenerationError: if the response cannot be parsed or validated.
        LLMError:              if the Claude API call itself fails.
    """
    system, human = build_lesson_gen_prompt(nlq, pred_sql, gold_sql, errors)
    raw = client.complete(system, human, temperature=0.0)

    return _parse_lesson(raw)


# ── Private helpers ────────────────────────────────────────────────────────────

def _extract_json(text: str) -> str:
    """
    Extract the first JSON object from a string.

    Uses a greedy regex to find the outermost { ... } block. This handles
    LLM responses that include leading prose ("Here is the lesson:") or a
    trailing sentence after the JSON.

    Returns the extracted JSON string, or raises LessonGenerationError if
    no JSON object is found.
    """
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if not match:
        raise LessonGenerationError(
            "No JSON object found in LLM response.", raw_output=text
        )
    return match.group(0)


def _parse_lesson(raw: str) -> Lesson:
    """
    Parse and validate a raw LLM response into a Lesson object.

    Steps:
      1. Extract JSON object from the response (handles leading/trailing prose)
      2. json.loads() — catches malformed JSON (single quotes, trailing commas)
      3. Lesson(**data) — Pydantic validates required fields and types

    Raises:
        LessonGenerationError: on any parse or validation failure.
    """
    json_str = _extract_json(raw)

    try:
        data = json.loads(json_str)
    except json.JSONDecodeError as e:
        raise LessonGenerationError(
            f"JSON parse error: {e}", raw_output=raw
        ) from e

    try:
        return Lesson(**data)
    except Exception as e:
        raise LessonGenerationError(
            f"Lesson validation error: {e}", raw_output=raw
        ) from e
